# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#

    Artist.create(name: "Scorpions",          country: "Germany",      language_song: "English")
    Artist.create(name: "Metallica",          country: "USA",          language_song: "English")
    Artist.create(name: "New order",          country: "Great Britan", language_song: "English")
    Artist.create(name: "Rammstein",          country: "Germany",      language_song: "German")
    Artist.create(name: "Lordi",              country: "Finland",      language_song: "English")
    Artist.create(name: "Eric Clapton",       country: "USA",          language_song: "English")
    Artist.create(name: "Johnny Cash",        country: "USA",          language_song: "English")
    Artist.create(name: "Bob Dylan",          country: "USA",          language_song: "English")
    Artist.create(name: "Madonna",            country: "USA",          language_song: "English")
    Artist.create(name: "Taylor Swift",       country: "USA",          language_song: "English")
    Artist.create(name: "Michaeil Jackson",   country: "USA",          language_song: "English")
    Artist.create(name: "two_pac",            country: "USA",          language_song: "English")
    Artist.create(name: "Eminem",             country: "USA",          language_song: "English")
    Artist.create(name: "Rise Agains",        country: "USA",          language_song: "English")

    Album.create(artist_id: 1,  name: "Blackout",                      released: "11-05-1982")
    Album.create(artist_id: 1,  name: "Return to Forever",             released: "14-08-2015")
    Album.create(artist_id: 2,  name: "Kill 'Em All'",                 released: "20-01-1983")
    Album.create(artist_id: 2,  name: "Ride the Lighthing",            released: "04-02-1984")
    Album.create(artist_id: 3,  name: "Music Complite",                released: "26-11-2015")
    Album.create(artist_id: 3,  name: "Brotherhood",                   released: "09-05-1986")
    Album.create(artist_id: 4,  name: "Mutter",                        released: "17-04-2001")
    Album.create(artist_id: 4,  name: "Rosenrot",                      released: "23-07-2005")
    Album.create(artist_id: 5,  name: "The Arockalypse",               released: "16-08-2009")
    Album.create(artist_id: 5,  name: "Scare Force One",               released: "19-04-2014")
    Album.create(artist_id: 6,  name: "Unplugged",                     released: "07-03-1992")
    Album.create(artist_id: 6,  name: "461 Ocean Boulevard",           released: "26-07-1974")
    Album.create(artist_id: 7,  name: "Ragged Old Flag",               released: "02-12-1974")
    Album.create(artist_id: 8,  name: "Desire",                        released: "03-08-1976")
    Album.create(artist_id: 9,  name: "Ray of Light",                  released: "09-03-1998")
    Album.create(artist_id: 9,  name: "Hart Candy",                    released: "06-07-2008")
    Album.create(artist_id: 10, name: "FearLess",                      released: "17-07-2008")
    Album.create(artist_id: 10, name: "Like a Prayer",                 released: "03-12-2010")
    Album.create(artist_id: 11, name: "Off the Wall",                  released: "18-01-2010")
    Album.create(artist_id: 12, name: "All Eyez on Me",                released: "04-08-2096")
    Album.create(artist_id: 12, name: "2Paclypse Now",                 released: "14-04-1991")
    Album.create(artist_id: 13, name: "Recovery",                      released: "24-08-2010")
    Album.create(artist_id: 13, name: "Infinite",                      released: "03-03-1996")
    Album.create(artist_id: 14,  name: "Endgame",                      released: "22-05-2011")
    Album.create(artist_id: 14,  name: "The Black Market",             released: "28-09-2014")

    Genre.create(name: "Rock")
    Genre.create(name: "Country")
    Genre.create(name: "Pop")
    Genre.create(name: "Rap")

    Author.create(first_name: "Джеймс",   last_name: "Хетфилд")
    Author.create(first_name: "Ларс",     last_name: "Ульрих")
    Author.create(first_name: "Мастейн",  last_name: "Дэйв")
    Author.create(first_name: "Майне",    last_name: "Клаус")
    Author.create(first_name: "Шенкер"  , last_name: "Рудольф")
    Author.create(first_name: "Линдеманн",last_name: "Тилль")
    Author.create(first_name: "Самнер",   last_name: "Бернард")
    Author.create(first_name: "Путаансуу",last_name: "Томи")
    Author.create(first_name: "Клэптон",  last_name: "Эрик")
    Author.create(first_name: "Кэш",      last_name: "Джонни")
    Author.create(first_name: "Дилан",    last_name: "Боб")
    Author.create(first_name: "Чиконне",  last_name: "Мадонна Луиза Вероника")
    Author.create(first_name: "Свифт",    last_name: "Тейлор Элисон")
    Author.create(first_name: "Джексон",  last_name: "Майкл")
    Author.create(first_name: "Шакур",    last_name: "Тупак Амару")
    Author.create(first_name: "Маршалл",  last_name: "Брюс Мэтерс Третий")
    Author.create(first_name: "Макилрот", last_name: "Тимоти")
    #scorpions
    Track.create(name: "Blackout",                  duration: 228, album_id: 1, genre_id: 1, author_id: 4, artist_id: 1)
    Track.create(name: "Can't Live Without You",    duration: 226, album_id: 1, genre_id: 1, author_id: 4, artist_id: 1)
    Track.create(name: "No One Like You",           duration: 324, album_id: 1, genre_id: 1, author_id: 4, artist_id: 1)
    Track.create(name: "You Give Me All I Need",    duration: 312, album_id: 1, genre_id: 1, author_id: 4, artist_id: 1)
    Track.create(name: "Now!",                      duration: 253, album_id: 1, genre_id: 1, author_id: 4, artist_id: 1)
    Track.create(name: "TEST",                      duration: 5000, album_id: 1, genre_id: 1, author_id: 4, artist_id: 1)

    Track.create(name: "Going Out With a Bang!",    duration: 342, album_id: 2, genre_id: 1, author_id: 4, artist_id: 1)
    Track.create(name: "We Built This House",       duration: 264, album_id: 2, genre_id: 1, author_id: 4, artist_id: 1)
    Track.create(name: "House of Cards",            duration: 341, album_id: 2, genre_id: 1, author_id: 4, artist_id: 1)
    Track.create(name: "All For One",               duration: 371, album_id: 2, genre_id: 1, author_id: 4, artist_id: 1)
    #Metallica
    Track.create(name: "Hit the Lights!",           duration: 231, album_id: 3, genre_id: 1, author_id: 1, artist_id: 2)
    Track.create(name: "The Four Horsemen",         duration: 183, album_id: 3, genre_id: 1, author_id: 1, artist_id: 2)
    Track.create(name: "Motorbreath",               duration: 145, album_id: 3, genre_id: 1, author_id: 1, artist_id: 2)

    Track.create(name: "Fight Fire with Fire",      duration: 441, album_id: 4, genre_id: 1, author_id: 2, artist_id: 2)
    Track.create(name: "Ride the Lightning ",       duration: 125, album_id: 4, genre_id: 1, author_id: 2, artist_id: 2)
    Track.create(name: "For Whom the Bell Tolls",   duration: 153, album_id: 4, genre_id: 1, author_id: 2, artist_id: 2)
    Track.create(name: "Fade to Black",             duration: 264, album_id: 4, genre_id: 1, author_id: 2, artist_id: 2)
    Track.create(name: "Escape",                    duration: 261, album_id: 4, genre_id: 1, author_id: 2, artist_id: 2)
    #new order
    Track.create(name: "Restless",                  duration: 141, album_id: 5, genre_id: 1, author_id: 5, artist_id: 3)
    Track.create(name: "Singularity",               duration: 122, album_id: 5, genre_id: 1, author_id: 5, artist_id: 3)
    Track.create(name: "Plastic",                   duration: 212, album_id: 5, genre_id: 1, author_id: 5, artist_id: 3)
    Track.create(name: "Paradise",                  duration: 242, album_id: 6, genre_id: 1, author_id: 5, artist_id: 3)
    #Rammstein
    Track.create(name: "Weirdo",                    duration: 137, album_id: 7, genre_id: 1, author_id: 6, artist_id: 4)
    Track.create(name: "Links 2-3-4",               duration: 165, album_id: 7, genre_id: 1, author_id: 6, artist_id: 4)
    Track.create(name: "Sonne",                     duration: 152, album_id: 7, genre_id: 1, author_id: 6, artist_id: 4)
    Track.create(name: "Ich will",                  duration: 122, album_id: 7, genre_id: 1, author_id: 6, artist_id: 4)

    Track.create(name: "Benzin",                    duration: 231, album_id: 8, genre_id: 1, author_id: 6, artist_id: 4)
    Track.create(name: "Mann gegen Mann",           duration: 431, album_id: 8, genre_id: 1, author_id: 6, artist_id: 4)
    Track.create(name: "Rosenrot",                  duration: 154, album_id: 8, genre_id: 1, author_id: 6, artist_id: 4)
    Track.create(name: "Spring",                    duration: 182, album_id: 8, genre_id: 1, author_id: 6, artist_id: 4)
    #lordi
    Track.create(name: "Hard Rock Hallelujah",      duration: 184, album_id: 9, genre_id: 1, author_id: 7, artist_id: 5)
    Track.create(name: "Who’s Your Daddy?",         duration: 123, album_id: 9, genre_id: 1, author_id: 7, artist_id: 5)
    Track.create(name: "It Snows in Hell",          duration: 143, album_id: 9, genre_id: 1, author_id: 7, artist_id: 5)
    Track.create(name: "Supermonstars",             duration: 126, album_id: 9, genre_id: 1, author_id: 7, artist_id: 5)

    Track.create(name: "Scare Force One",           duration: 235, album_id: 10, genre_id: 1, author_id: 7, artist_id: 5)
    Track.create(name: "She's a Demon",             duration: 173, album_id: 10, genre_id: 1, author_id: 7, artist_id: 5)
    Track.create(name: "Monster is My Name",        duration: 153, album_id: 10, genre_id: 1, author_id: 7, artist_id: 5)
    Track.create(name: "House of Ghosts",           duration: 129, album_id: 10, genre_id: 1, author_id: 7, artist_id: 5)
    #rise against
    Track.create(name: "Endgame",                   duration: 123, album_id: 23, genre_id: 1, author_id: 17, artist_id: 14)
    Track.create(name: "Make It Stop",              duration: 234, album_id: 23, genre_id: 1, author_id: 17, artist_id: 14)
    Track.create(name: "Survivor Guilt",            duration: 127, album_id: 23, genre_id: 1, author_id: 17, artist_id: 14)
    Track.create(name: "This Is Letting Go",        duration: 123, album_id: 23, genre_id: 1, author_id: 17, artist_id: 14)

    Track.create(name: "The Great Die-Off",         duration: 142, album_id: 24, genre_id: 1, author_id: 17, artist_id: 14)
    Track.create(name: "The Black Market",          duration: 162, album_id: 24, genre_id: 1, author_id: 17, artist_id: 14)
    Track.create(name: "Methadone",                 duration: 173, album_id: 24, genre_id: 1, author_id: 17, artist_id: 14)
    Track.create(name: "Tragedy + Time",            duration: 132, album_id: 24, genre_id: 1, author_id: 17, artist_id: 14)

    Track.create(name: "Signe",                     duration: 153, album_id: 11, genre_id: 2, author_id: 9, artist_id: 6)
    Track.create(name: "Before You Accuse Me",      duration: 175, album_id: 11, genre_id: 2, author_id: 9, artist_id: 6)
    Track.create(name: "Hey Hey",                   duration: 124, album_id: 11, genre_id: 2, author_id: 9, artist_id: 6)
    Track.create(name: "Tears in Heaven",           duration: 143, album_id: 11, genre_id: 2, author_id: 9, artist_id: 6)

    Track.create(name: "Motherless Children",       duration: 432, album_id: 12, genre_id: 2, author_id: 9, artist_id: 6)
    Track.create(name: "Give Me Strength",          duration: 285, album_id: 12, genre_id: 2, author_id: 9, artist_id: 6)
    Track.create(name: "Willie and the Hand Jive",  duration: 284, album_id: 12, genre_id: 2, author_id: 9, artist_id: 6)
    Track.create(name: "Get Ready",                 duration: 231, album_id: 12, genre_id: 2, author_id: 9, artist_id: 6)

    Track.create(name: "Ragged Old Flag",           duration: 125, album_id: 13, genre_id: 2, author_id: 10, artist_id: 7)
    Track.create(name: "Don't Go Near the Water",   duration: 164, album_id: 13, genre_id: 2, author_id: 10, artist_id: 7)
    Track.create(name: "All I Do is Drive",         duration: 126, album_id: 13, genre_id: 2, author_id: 10, artist_id: 7)
    Track.create(name: "Southern Comfort",          duration: 153, album_id: 13, genre_id: 2, author_id: 10, artist_id: 7)

    Track.create(name: "Hurricane",                 duration: 351, album_id: 14, genre_id: 2, author_id: 11, artist_id: 8)
    Track.create(name: "Isis",                      duration: 127, album_id: 14, genre_id: 2, author_id: 11, artist_id: 8)
    Track.create(name: "Mozambique",                duration: 145, album_id: 14, genre_id: 2, author_id: 11, artist_id: 8)
    Track.create(name: "One More Cup of Coffee",    duration: 134, album_id: 14, genre_id: 2, author_id: 11, artist_id: 8)

    Track.create(name: "Drowned World",             duration: 534, album_id: 15, genre_id: 3, author_id: 12, artist_id: 9)
    Track.create(name: "Swim",                      duration: 331, album_id: 15, genre_id: 3, author_id: 12, artist_id: 9)
    Track.create(name: "Ray of Light",              duration: 432, album_id: 15, genre_id: 3, author_id: 12, artist_id: 9)
    Track.create(name: "Candy Perfume Girl",        duration: 234, album_id: 15, genre_id: 3, author_id: 12, artist_id: 9)

    Track.create(name: "Like a Prayer",             duration: 432, album_id: 16, genre_id: 3, author_id: 12, artist_id: 9)
    Track.create(name: "Express Yourself",          duration: 212, album_id: 16, genre_id: 3, author_id: 12, artist_id: 9)
    Track.create(name: "Love Song",                 duration: 124, album_id: 16, genre_id: 3, author_id: 12, artist_id: 9)
    Track.create(name: "Till Death Do Us Part",     duration: 153, album_id: 16, genre_id: 3, author_id: 12, artist_id: 9)

    #eminem
    Track.create(name: "Never Enough",              duration: 234, album_id: 22, genre_id: 4, author_id: 16, artist_id: 13)
    Track.create(name: "Like Toy Soldiers",         duration: 312, album_id: 22, genre_id: 4, author_id: 16, artist_id: 13)
    Track.create(name: "Rain Man",                  duration: 435, album_id: 22, genre_id: 4, author_id: 16, artist_id: 13)
    Track.create(name: "Just Lose it",              duration: 231, album_id: 22, genre_id: 4, author_id: 16, artist_id: 13)

	  Track.create(name: "Not Afraid",                duration: 234, album_id: 23, genre_id: 4, author_id: 16, artist_id: 13)
    Track.create(name: "Space Bound",               duration: 421, album_id: 23, genre_id: 4, author_id: 16, artist_id: 13)
    Track.create(name: "No Love",                   duration: 234, album_id: 23, genre_id: 4, author_id: 16, artist_id: 13)
    Track.create(name: "Love the Way You Lie",      duration: 324, album_id: 23, genre_id: 4, author_id: 16, artist_id: 13)
    #swift
    Track.create(name: "Love Story",                duration: 234, album_id: 17, genre_id: 3, author_id: 13, artist_id: 10)
    Track.create(name: "White Horse",               duration: 231, album_id: 17, genre_id: 3, author_id: 13, artist_id: 10)
    Track.create(name: "You Belong with Me",        duration: 132, album_id: 17, genre_id: 3, author_id: 13, artist_id: 10)
    Track.create(name: "Tell Me Why",               duration: 212, album_id: 17, genre_id: 3, author_id: 13, artist_id: 10)

    Track.create(name: "Mine",                      duration: 312, album_id: 18, genre_id: 3, author_id: 13, artist_id: 10)
    Track.create(name: "Back to December",          duration: 432, album_id: 18, genre_id: 3, author_id: 13, artist_id: 10)
    Track.create(name: "Speak Now",                 duration: 342, album_id: 18, genre_id: 3, author_id: 13, artist_id: 10)
    Track.create(name: "The Story of Us",           duration: 421, album_id: 18, genre_id: 3, author_id: 13, artist_id: 10)
    #Jackson
    Track.create(name: "Of the Wall",               duration: 421, album_id: 19, genre_id: 3, author_id: 14, artist_id: 11)
    Track.create(name: "Falling in Love",           duration: 432, album_id: 19, genre_id: 3, author_id: 14, artist_id: 11)
    Track.create(name: "She is out of My Life",     duration: 123, album_id: 19, genre_id: 3, author_id: 14, artist_id: 11)
    Track.create(name: "Rock with You",             duration: 84, album_id: 19, genre_id: 3, author_id: 14, artist_id: 11)
    #2pac
    Track.create(name: "I Don't Give a Fuck",       duration: 83, album_id: 20, genre_id: 4, author_id: 15, artist_id: 12)
    Track.create(name: "Crooked Ass Nigga",         duration: 423, album_id: 20, genre_id: 4, author_id: 15, artist_id: 12)
    Track.create(name: "Young Black Male",          duration: 223, album_id: 20, genre_id: 4, author_id: 15, artist_id: 12)
    Track.create(name: "Rebel of the Underground",  duration: 432, album_id: 20, genre_id: 4, author_id: 15, artist_id: 12)

	  Track.create(name: "California Love",           duration: 321, album_id: 21, genre_id: 4, author_id: 15, artist_id: 12)
    Track.create(name: "Life Goes On",              duration: 363, album_id: 21, genre_id: 4, author_id: 15, artist_id: 12)
    Track.create(name: "How Do U Want It",          duration: 254, album_id: 21, genre_id: 4, author_id: 15, artist_id: 12)
    Track.create(name: "Only God Can Judge Me",     duration: 145, album_id: 21, genre_id: 4, author_id: 15, artist_id: 12)






    Carrier.create(name: "Заказ №1")
  #  Carrier.create(name: "collection")
  #  Carrier.create(name: "collection2")
  #  Carrier.create(name: "carrier4")
  #  Carrier.create(name: "carrier5")
  #  Carrier.create(name: "carrier6")

    TypeCarrier.create(name: "Disk CD",          price_of_record: 500,   max_duration: 4320, capacity: 700)
    TypeCarrier.create(name: "Disk DVD",         price_of_record: 1500,  max_duration: 18000, capacity: 4700)
    TypeCarrier.create(name: "Flash Drive 8gb",  price_of_record: 3000,  max_duration: 37800, capacity: 8000)
    TypeCarrier.create(name: "Flash Drive 16gb", price_of_record: 6000,  max_duration: 72000, capacity: 16000)
    TypeCarrier.create(name: "Flash Drive 32gb", price_of_record: 12000, max_duration: 144000, capacity: 32000)
